### ISSUE TITLE
Retrospective

### ISSUE THREAD

**Issue by unbreaking-V** [ivysochyn/textiv#15]
### Description:

- [x] Corrective actions from the retrospective of the previous sprint were written down
- [x] The implementation of the corrective actions was monitored (e.g. tasks appeared in the sprint backlog)

**Comment by Zajancz** [comment]
**Tasks to work on from first sprint:**

- [ ] Create correct mapping in TextTransformerController
- [ ] Fix Rest warnings in TextTransformerController
- [ ] Correct some transformation functions 
- [ ] Slightly correct the UML diagram

**Comment by unbreaking-V** [comment]
End.
